### ISSUE TITLE
Windows support may be limited

### ISSUE THREAD

**Issue by apiszcz** [jarun/pdd#4]
FYI:
> lib\python\python lib\pdd\pdd.py
Traceback (most recent call last):
  File "lib\pdd\pdd.py", line 412, in <module>
    main()
  File "lib\pdd\pdd.py", line 244, in main
    args = parse_args()
  File "lib\pdd\pdd.py", line 237, in parse_args
    t.tm_hour, t.tm_min, t.tm_sec, t.tm_zone))
AttributeError: 'time.struct_time' object has no attribute 'tm_zone'

**Comment by jarun** [comment]
What's your version on python3?

It seems v3.6 has it:

https://docs.python.org/3/library/time.html

Can you please confirm?

**Comment by apiszcz** [comment]
3.5

On Fri, May 25, 2018 at 8:59 AM, Arun Prakash Jana <notifications@github.com

**Comment by jarun** [comment]
Can you please confirm it works on 3.6?

Then I can add a patch only for 3.5 (basically disable it).

**Comment by jarun** [comment]
I do not have Windows.

**Comment by apiszcz** [comment]
3.6 works fine, interesting.


On Fri, May 25, 2018 at 9:03 AM, Arun Prakash Jana <notifications@github.com

**Comment by apiszcz** [comment]
one more thing, WINDOWS issue
'setterm' is not recognized as an internal or external command,
operable program or batch file.

you can just state for LINUX only, to avoid these questions


On Fri, May 25, 2018 at 9:03 AM, Arun Prakash Jana <notifications@github.com

**Comment by jarun** [comment]
I will drop support for Windows.

**Comment by jarun** [comment]
Linux and OS X work fine I believe.

**Comment by jarun** [comment]
@dertuxmalwieder would it be possible for you to sanitize this for Windows? If not, I will drop the support for Windows.

**Comment by dertuxmalwieder** [comment]
What would the `setterm` command do on non-Windows systems? Because it seems to me that you can just wrap it in "if not windows...".

**Comment by jarun** [comment]
On Linux I noticed the cursor keeps moving left to right without it. If you comment it out, how does it behave on Windows?

**Comment by dertuxmalwieder** [comment]
I understand. I can't test it before tomorrow, but maybe [this](https://github.com/GijsTimmers/cursor/blob/master/cursor/cursor.py) helps to solve the problem regardless of if it even exists?

**Comment by jarun** [comment]
If we see the problem on Windows we can definitely try this.

**Comment by jarun** [comment]
It would be great if you can check this and send a patch if it exists.

**Comment by dertuxmalwieder** [comment]
I'll look into it when I'm back on my Windows machine.

**Comment by jarun** [comment]
Awesome! :+1:

**Comment by apiszcz** [comment]
it is fine just prints the error messages
pdd.py -s
'setterm' is not recognized as an internal or external command,
operable program or batch file.
1.058s
'setterm' is not recognized as an internal or external command,
operable program or batch file.

On Fri, May 25, 2018 at 9:26 AM, Arun Prakash Jana <notifications@github.com

**Comment by dertuxmalwieder** [comment]
Confirmed on the PowerShell, including the jumping cursor (although barely obvious).

**Comment by jarun** [comment]
I think it would be a good idea to patch for Windows, however for Linux we can retain the standard APIs (same as now).

**Comment by dertuxmalwieder** [comment]
Tested in PowerShell:

    diff --git a/pdd b/pdd
    index 5a16bcc..650cb48 100755
    --- a/pdd
    +++ b/pdd
    @@ -26,6 +26,12 @@ import math
     import os
     import sys
     import time
    +if os.name == 'nt':
    +    import ctypes
    +
    +    class _CursorInfo(ctypes.Structure):
    +        _fields_ = [("size", ctypes.c_int),
    +                    ("visible", ctypes.c_byte)]
     
     # Globals
     
    @@ -361,7 +367,14 @@ def main():
                 raise ValueError('negative value')
     
             if args.quiet is False:
    -            os.system('setterm -cursor off')
    +            if os.name != 'nt':
    +                os.system('setterm -cursor off')
    +            else:
    +                ci = _CursorInfo()
    +                handle = ctypes.windll.kernel32.GetStdHandle(-11)
    +                ctypes.windll.kernel32.GetConsoleCursorInfo(handle, ctypes.byref(ci))
    +                ci.visible = False
    +                ctypes.windll.kernel32.SetConsoleCursorInfo(handle, ctypes.byref(ci))
     
             try:
                 while True:
    @@ -382,7 +395,14 @@ def main():
                 print('\r{0:02d}h {1:02d}m {2:02d}s  '.format(h, m, s), end='\b\b\n', flush=True)
             finally:
                 if args.quiet is False:
    -                os.system('setterm -cursor on')
    +                if os.name != 'nt':
    +                    os.system('setterm -cursor on')
    +                else:
    +                    ci = _CursorInfo()
    +                    handle = ctypes.windll.kernel32.GetStdHandle(-11)
    +                    ctypes.windll.kernel32.GetConsoleCursorInfo(handle, ctypes.byref(ci))
    +                    ci.visible = True
    +                    ctypes.windll.kernel32.SetConsoleCursorInfo(handle, ctypes.byref(ci))
     
         # Stopwatch
         if args.stopwatch:

**Comment by jarun** [comment]
Awesome! Thank you very much!

**Comment by jarun** [comment]
@apiszcz can you please confirm the original issue works as expected now?

**Comment by apiszcz** [comment]
latest version works, great, no issues! thank you.

**Comment by jarun** [comment]
Thank you for the confirmation! Have fun!
